### ISSUE TITLE
LED Commands

### ISSUE THREAD

**Issue by rovaden** [Yeti-Robotics/olaf-java-2021#19]
Rainbow is currently broken and Set YEti blue should be checked.

**Comment by rovaden** [comment]
rainbow command is broken and needs to be fixed
should make a gradient command (first colors should be yeti blue to white)
the hsv values for yeti blue need to be checked. what does the method even use lmao ahahaha

**Comment by Flipkickisreal** [comment]
everytime I try to define the rainbowSetFirst it breaks something.

**Comment by rovaden** [comment]
i'll take a look at it and see if i can fix it

**Comment by Yukigamine** [comment]
Rainbow command is fixed, and Gradient command has been started. Code builds. From now on do not merge changes to main unless the code builds.

**Comment by rovaden** [comment]
no leds on robot right now. dev is still in progress but not needed.
