### ISSUE TITLE
Shooter subsystem

### ISSUE THREAD

**Issue by rovaden** [Yeti-Robotics/olaf-java-2021#20]
doesn't work lmao
- spin method redundant, which to the shoot one
- refactor methods so that it's move flywheel instead of just **shoot**
- change calc hood angle to hood subsystem lmao and change the distance calc line to be in hood subsystem ahaha
- change encoder method to change to velocity  or dont that's also okay. just think about it
- initilize the shooterstatus var ennum as off in the contrustuors for the shooter subsystem
-

**Comment by hmagan** [comment]
done

**Comment by Yukigamine** [comment]
Sweet. Open a pull request and link it to this issue by writing "fixes #20" in it.
