### ISSUE TITLE
Recorded playback is sometimes crunchy

### ISSUE THREAD

**Issue by ValerieBG** [Yeti-Robotics/olaf-java-2021#73]
Sometimes when you play back a recording, it's way off and super jittery like it's browning out or crunching gears. It seems to vary from recording to recording, but is consistent when replaying the same recording.

**Comment by ValerieBG** [comment]
It seems to consistently happen when the robot is restarted (ie. changing batteries)?

**Comment by rovaden** [comment]
we decided not to fix this
